# Generated by Django 5.2.13 on 2026-04-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('niveau_etudes', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat')], max_length=5)),
                ('os_principal', models.CharField(choices=[('parrot', 'Parrot OS / Kali Linux'), ('windows', 'Windows'), ('macos', 'macOS'), ('android', 'Android/iOS')], max_length=10)),
                ('utilise_2fa', models.BooleanField(default=False, verbose_name='Double Authentification')),
                ('gestionnaire_mdp', models.BooleanField(default=False, verbose_name='Gestionnaire de MDP')),
                ('maj_auto', models.BooleanField(default=False, verbose_name='Mises à jour automatiques')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
